apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bggns
  labels:
    name: bgg-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-cm
  labels:
    name: bgg-cm
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns